In [3]:
# Cell 1 — Load Events Dataset

from pathlib import Path
import pandas as pd

# Define events directory
EVENTS_DIR = Path(
    r"C:\Projects\Infer RozviDrought\data\events"
)

# Choose primary validation file
EVENTS_FILE = EVENTS_DIR / "Events.xlsx"

print("Using events file:", EVENTS_FILE)

# Load dataset
events_df = pd.read_excel(EVENTS_FILE)

# Basic inspection
print("\nShape:", events_df.shape)
print("\nColumns:")
print(events_df.columns.tolist())

# Preview first rows
events_df.head()

Using events file: C:\Projects\Infer RozviDrought\data\events\Events.xlsx

Shape: (19, 14)

Columns:
['ZIMBABWE MAJOR DROUGHT EVENTS – CHRONOLOGICAL TIMELINE (1902–2024)', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

,ZIMBABWE MAJOR DROUGHT EVENTS – CHRONOLOGICAL TIMELINE (1902–2024),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Sources: EM-DAT/CRED; FAO/WFP; OCHA; Zimbabwe ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ID,Event Period,Growing Season,El Niño\nAssociation,Duration\n(Months),Rainfall\nDeficit (%),Affected Regions\n(Research-Validated),Agricultural Impact,Population\nAffected,Government Response / Declarations,Economic Cost\n(Estimated),Severity\nScore (1–5),Severity Label,Key Notes / Sources
2,1,1902–1903,1902/03,No,12,~30%,Matabeleland & Mashonaland. Colonial famine re...,Crop failures; famine in Matabeleland & Mashon...,~0.5M est.,Colonial famine relief limited to mission stat...,Unknown,2,2 – Moderate,One of first recorded colonial-era droughts
3,2,1911–1912,1911/12,No,10,~25%,Nationwide. Among the worst consecutive dry sp...,Widespread crop failure; cattle losses in Mata...,~0.4M est.,Colonial Dept. of Agriculture distributed seed...,Unknown,2,2 – Moderate,Part of Takuva's PhD study on 1911–1992 drough...
4,3,1921–1922,1921/22,Yes (moderate),10,~30%,Nationwide; no province-level breakdown in ava...,Poor harvests; grain shortages; livestock losses,~0.5M est.,Government grain distribution; mission station...,Unknown,2,2 – Moderate,Low population base relative to later events

In [4]:
# Cell 2 — Fix Headers and Clean Events Table

import pandas as pd
from pathlib import Path

EVENTS_FILE = Path(
    r"C:\Projects\Infer RozviDrought\data\events\Events.xlsx"
)

# Reload while skipping the title row
events_df = pd.read_excel(EVENTS_FILE, header=1)

# Clean column names
events_df.columns = [str(col).strip() for col in events_df.columns]

print("Cleaned Shape:", events_df.shape)

print("\nCleaned Columns:")
for col in events_df.columns:
    print("-", col)

# Preview dataset
events_df.head()

Cleaned Shape: (18, 14)

Cleaned Columns:
- Sources: EM-DAT/CRED; FAO/WFP; OCHA; Zimbabwe Meteorological Services (weatherzw.org.zw); Afrobarometer/Veritaszim; UNICEF; ReliefWeb; peer-reviewed literature (Takuva 2022; MDPI 2020; Tandfonline 2025); UN SDGs Zimbabwe; Additional validated sources for Affected Regions column: Chigodora, J. (1997) Drought Network News 9(1), UNL Digital Commons; Takuva, T. (2022) PhD thesis, Stellenbosch University; Tandfonline (2025) 'The Hunger Games: Politics and Drought in Post-Colonial Zimbabwe, 1980–1992'; MDPI Sustainability (2020) 'Drought Risk to Agricultural Systems in Zimbabwe'; Springer (2021) 'Spatio-temporal dynamics of drought in Zimbabwe 1990–2020'; FAO/WFP Special Report on Zimbabwe (May 2002); FAO GIEWS Africa Report No.1 (April 2002); OCHA Zimbabwe Drought Flash Appeal (May 2024); UNICEF Zimbabwe Humanitarian Situation Reports (2016, 2024); GOZ 2016–2017 Drought Disaster Appeal (ReliefWeb); CIWA/IWMI Drought Resilience Profile Zimbabwe; El Niño Ready Nations — Zimbabwe Case Study; Mukwada & Manatsa (2013) Geographia Polonica 86(4); Cameron, H. (2018) 'State-Organized Starvation', Genocide Studies and Prevention 12(1); ACT Alliance RRF 07 2024 Zimbabwe Drought.
- Unnamed: 1
- Unnamed: 2
- Unnamed: 3
- Unnamed: 4
- Unnamed: 5
- Unnamed: 6
- Unnamed: 7
- Unnamed: 8
- Unnamed: 9
- Unnamed: 10
- Unnamed: 11
- Unnamed: 12
- Unnamed: 13

,"Sources: EM-DAT/CRED; FAO/WFP; OCHA; Zimbabwe Meteorological Services (weatherzw.org.zw); Afrobarometer/Veritaszim; UNICEF; ReliefWeb; peer-reviewed literature (Takuva 2022; MDPI 2020; Tandfonline 2025); UN SDGs Zimbabwe; Additional validated sources for Affected Regions column: Chigodora, J. (1997) Drought Network News 9(1), UNL Digital Commons; Takuva, T. (2022) PhD thesis, Stellenbosch University; Tandfonline (2025) 'The Hunger Games: Politics and Drought in Post-Colonial Zimbabwe, 1980–1992'; MDPI Sustainability (2020) 'Drought Risk to Agricultural Systems in Zimbabwe'; Springer (2021) 'Spatio-temporal dynamics of drought in Zimbabwe 1990–2020'; FAO/WFP Special Report on Zimbabwe (May 2002); FAO GIEWS Africa Report No.1 (April 2002); OCHA Zimbabwe Drought Flash Appeal (May 2024); UNICEF Zimbabwe Humanitarian Situation Reports (2016, 2024); GOZ 2016–2017 Drought Disaster Appeal (ReliefWeb); CIWA/IWMI Drought Resilience Profile Zimbabwe; El Niño Ready Nations — Zimbabwe Case Study; Mukwada & Manatsa (2013) Geographia Polonica 86(4); Cameron, H. (2018) 'State-Organized Starvation', Genocide Studies and Prevention 12(1); ACT Alliance RRF 07 2024 Zimbabwe Drought.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,ID,Event Period,Growing Season,El Niño\nAssociation,Duration\n(Months),Rainfall\nDeficit (%),Affected Regions\n(Research-Validated),Agricultural Impact,Population\nAffected,Government Response / Declarations,Economic Cost\n(Estimated),Severity\nScore (1–5),Severity Label,Key Notes / Sources
1,1,1902–1903,1902/03,No,12,~30%,Matabeleland & Mashonaland. Colonial famine re...,Crop failures; famine in Matabeleland & Mashon...,~0.5M est.,Colonial famine relief limited to mission stat...,Unknown,2,2 – Moderate,One of first recorded colonial-era droughts
2,2,1911–1912,1911/12,No,10,~25%,Nationwide. Among the worst consecutive dry sp...,Widespread crop failure; cattle losses in Mata...,~0.4M est.,Colonial Dept. of Agriculture distributed seed...,Unknown,2,2 – Moderate,Part of Takuva's PhD study on 1911–1992 drough...
3,3,1921–1922,1921/22,Yes (moderate),10,~30%,Nationwide; no province-level breakdown in ava...,Poor harvests; grain shortages; livestock losses,~0.5M est.,Government grain distribution; mission station...,Unknown,2,2 – Moderate,Low population base relative to later events
4,4,1932–1933,1932/33,No,12,~35%,Nationwide; specific provinces not disaggregat...,Severe crop failure; cattle mortality; famine ...,~0.7M est.,Colonial emergency food distribution; maize im...,Unknown,3,3 – Severe,Great Depression compounded economic vulnerabi...

In [5]:
# Cell 3 — Inspect Raw Excel Rows

raw_events_df = pd.read_excel(EVENTS_FILE, header=None)

print("Raw shape:", raw_events_df.shape)

# Show first 8 rows so we can identify the true header row
raw_events_df.head(8)

Raw shape: (20, 14)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,ZIMBABWE MAJOR DROUGHT EVENTS – CHRONOLOGICAL ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sources: EM-DAT/CRED; FAO/WFP; OCHA; Zimbabwe ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ID,Event Period,Growing Season,El Niño\nAssociation,Duration\n(Months),Rainfall\nDeficit (%),Affected Regions\n(Research-Validated),Agricultural Impact,Population\nAffected,Government Response / Declarations,Economic Cost\n(Estimated),Severity\nScore (1–5),Severity Label,Key Notes / Sources
3,1,1902–1903,1902/03,No,12,~30%,Matabeleland & Mashonaland. Colonial famine re...,Crop failures; famine in Matabeleland & Mashon...,~0.5M est.,Colonial famine relief limited to mission stat...,Unknown,2,2 – Moderate,One of first recorded colonial-era droughts
4,2,1911–1912,1911/12,No,10,~25%,Nationwide. Among the worst consecutive dry sp...,Widespread crop failure; cattle losses in Mata...,~0.4M est.,Colonial Dept. of Agriculture distributed seed...,Unknown,2,2 – Moderate,Part of Takuva's PhD study on 1911–1992 drough...
5,3,1921–1922,1921/22,Yes (moderate),10,~30%,Nationwide; no province-level breakdown in ava...,Poor harvests; grain shortages; livestock losses,~0.5M est.,Government grain distribution; mission station...,Unknown,2,2 – Moderate,Low population base relative to later events
6,4,1932–1933,1932/33,No,12,~35%,Nationwide; specific provinces not disaggregat...,Severe crop failure; cattle mortality; famine ...,~0.7M est.,Colonial emergency food distribution; maize im...,Unknown,3,3 – Severe,Great Depression compounded economic vulnerabi...
7,5,1946–1947,1946/47,No,11,~30%,Nationwide; especially severe in Bulilima (sou...,Widespread crop failure; grain shortages; live...,~1M est.,Government grain imports; Grain Marketing Boar...,Unknown,3,3 – Severe,Remembered for severity in Bulilima and southw...